name: Test
on:
  pull_request: null
  push:
    branches:
    - master
jobs:
  run:
    name: Run ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js 10.x
      uses: actions/setup-node@v1.4.0
      with:
        node-version: 10.x

    - name: npm install
      run: npm install

    - name: Lint
      run: npm run format-check

    - name: Exec action
      run: npm run action

    - name: Display version
      run: stack --version
